
import Entidades.BancoDeDados;
import Entidades.Bibliotecario;
import Entidades.Livro;
import Entidades.Usuario;
import Entidades.Emprestimo;
import java.lang.reflect.Array;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;



/**
 *
 * @author samuelcds
 */

public class Emprestimos extends javax.swing.JFrame {
    Bibliotecario bibliotecario;
    List<Livro> livro;
    Usuario user;
    LocalDate devolucao;
    LocalDate dataAtual = LocalDate.now();
    Double multa;

    /**
     * Creates new form Emprestimo
     */
    
    public Emprestimos() {
        initComponents();
    }
    
    public Emprestimos(Usuario user, List<Livro> livro) {
        initComponents();
        
        this.user = user;
        this.livro = livro;
        
        textoUsuario.setText(user.getUsuario());
        
        BancoDeDados bancoDeDados = BancoDeDados.getInstance();
        String[] lv = bancoDeDados.getLivro()
                             .stream()
                             .map(Livro::getTitulo)
                             .toArray(String[]::new);
        
        livroSelecionado.setText(Arrays.toString(lv));
        
        if (user.isProfessor()) {
            devolucao = dataAtual.plusDays(60);
            
            // Define um formato (por exemplo, dd/MM/yyyy)
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            
            // Converte LocalDate para String
            String dataFormatada = dataAtual.format(formato);
            
            dataDevolucao.setText(dataFormatada);
            multa = 0.80;
            valorMulta.setText("Valor da multa pelo atraso: 0,80/dia");
        }
        
        if (!(user.isProfessor())) {
            devolucao = dataAtual.plusDays(30);
            
            // Define um formato (por exemplo, dd/MM/yyyy)
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            
            // Converte LocalDate para String
            String dataFormatada = dataAtual.format(formato);
            
            dataDevolucao.setText(dataFormatada);
            multa = 0.50;
            valorMulta.setText("Valor da multa pelo atraso: 0,50/dia");
        }
    }
    
    public Emprestimos(Bibliotecario bibliotecario, Usuario user, List<Livro> livro) {
        initComponents();
        
        this.bibliotecario = bibliotecario;
        this.user = user;
        this.livro = livro;
        textoUsuario.setText(user.getUsuario());
        
        BancoDeDados bancoDeDados = BancoDeDados.getInstance();
        String[] lv = bancoDeDados.getLivro()
                             .stream()
                             .map(Livro::getTitulo)
                             .toArray(String[]::new);
        
        livroSelecionado.setText(Arrays.toString(lv));
        
        if (user.isProfessor()) {
            devolucao = dataAtual.plusDays(40);
            
            // Define um formato (por exemplo, dd/MM/yyyy)
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            
            // Converte LocalDate para String
            String dataFormatada = dataAtual.format(formato);
            
            dataDevolucao.setText(dataFormatada);
            multa = 2.00;
            valorMulta.setText("Valor da multa pelo atraso: 2,00/dia");
        }
        
        if (!(user.isProfessor())) {
            devolucao = dataAtual.plusDays(20);
            
            // Define um formato (por exemplo, dd/MM/yyyy)
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            
            // Converte LocalDate para String
            String dataFormatada = dataAtual.format(formato);
            
            dataDevolucao.setText(dataFormatada);
            multa = 1.50;
            valorMulta.setText("Valor da multa pelo atraso: 1,50/dia");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        livroSelecionado = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataDevolucao = new javax.swing.JTextPane();
        botaoFinalizar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        valorMulta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Annapurna SIL", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Realizar Emprestimo");

        jLabel2.setText("Usuario:");

        textoUsuario.setEditable(false);
        textoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Livros Selecionados:");

        livroSelecionado.setEditable(false);
        livroSelecionado.setColumns(20);
        livroSelecionado.setRows(5);
        jScrollPane1.setViewportView(livroSelecionado);

        jLabel4.setText("Data para devolução:");

        dataDevolucao.setEditable(false);
        jScrollPane2.setViewportView(dataDevolucao);

        botaoFinalizar.setText("Finalizar Emprestimo");
        botaoFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFinalizarActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        valorMulta.setEditable(false);
        valorMulta.setColumns(2);
        valorMulta.setRows(2);
        valorMulta.setTabSize(2);
        valorMulta.setText("Valor da multa pelo atraso:");
        jScrollPane3.setViewportView(valorMulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoUsuario)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botaoCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(botaoFinalizar))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoFinalizar)
                            .addComponent(botaoCancelar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoUsuarioActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFinalizarActionPerformed
        if (bibliotecario == null){
            for (Livro i : livro) {
                if (i.isLivroRaro() && (bibliotecario == null)) {
                    JOptionPane.showMessageDialog(null, "Você não possui autorização para realizar o Empréstimo de um Livro Raro, solicite a um bibliocário para realizar o empréstimo.é", "Erro", JOptionPane.ERROR_MESSAGE);
                    break;
                }
                else {
                Emprestimo emprestimo = new Emprestimo(user, livro, devolucao, multa);
                        }
            }
        }
        Emprestimo emprestimo = new Emprestimo(user, bibliotecario,livro, devolucao, multa);
        
        BancoDeDados banquinho = BancoDeDados.getInstance();
        banquinho.addEmprestimo(emprestimo);
        
        this.dispose();
    }//GEN-LAST:event_botaoFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Emprestimos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoFinalizar;
    private javax.swing.JTextPane dataDevolucao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea livroSelecionado;
    private javax.swing.JTextField textoUsuario;
    private javax.swing.JTextArea valorMulta;
    // End of variables declaration//GEN-END:variables
}
