package bceplus;




/*
 * ClioDeDados;
import Entidades.Empreck nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author samuelcds
 */

import Entidades.BancoDeDados;
import Entidades.Emprestimo;
import Entidades.Livro;
import Entidades.Administrador;
import Entidades.Bibliotecario;
import Entidades.Usuario;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;


public class ListaBibliotecarios extends javax.swing.JFrame {

    private void atualizarTabela() {
        BancoDeDados bancoDeDados = BancoDeDados.getInstance();
        List<Bibliotecario> listaBibliotecarios = bancoDeDados.getBibliotecario();

        // Limpa a tabela
        DefaultTableModel modelo = (DefaultTableModel) tabelaBibliotecarios.getModel();
        modelo.setRowCount(0);

        // Recarrega a tabela com os dados atualizados
        for (Bibliotecario bibliotecario : listaBibliotecarios) {
            modelo.addRow(new Object[]{
                bibliotecario.getId(),
                bibliotecario.getNome(),
                bibliotecario.getGenero(),
                bibliotecario.getCpf(),
                bibliotecario.getUsuario(),
                bibliotecario.getSenha(),
                bibliotecario.getPrimeiroLogin()
            });
        }
    }
    
    public ListaBibliotecarios() {
        initComponents();
        
        BancoDeDados bancoDeDados = BancoDeDados.getInstance();
        List<Bibliotecario> listaBibliotecarios = bancoDeDados.getBibliotecario();
        
        tabelaBibliotecarios.getColumnModel().getColumn(0).setPreferredWidth(10);
        tabelaBibliotecarios.getColumnModel().getColumn(5).setPreferredWidth(40);
        

        DefaultTableModel modelo = (DefaultTableModel) tabelaBibliotecarios.getModel();
        for (Bibliotecario bibliotecario : listaBibliotecarios) {
            modelo.addRow(new Object[]{
                bibliotecario.getId(),
                bibliotecario.getNome(),
                bibliotecario.getGenero(),
                bibliotecario.getCpf(),
                bibliotecario.getUsuario(),
                bibliotecario.getSenha(),
                bibliotecario.getPrimeiroLogin()
            });
        }
        
        tabelaBibliotecarios.getSelectionModel().addListSelectionListener(e -> {
            // Verifica se a seleção está em curso e se há uma linha selecionada
            if (!e.getValueIsAdjusting()) {
                boolean linhaSelecionada = tabelaBibliotecarios.getSelectedRow() != -1;

                // Ativa os botões somente se uma linha estiver selecionada
                botaoEditar.setEnabled(linhaSelecionada);
                botaoRemover.setEnabled(linhaSelecionada);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaBibliotecarios = new javax.swing.JTable();
        cadastrarNovoUsuario = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Annapurna SIL", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bibliotecários");

        tabelaBibliotecarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Gênero", "CPF", "Usuário", "Senha", "Primeiro Login"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaBibliotecarios);

        cadastrarNovoUsuario.setText("Cadastrar Novo Bibliotecário");
        cadastrarNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarNovoUsuarioActionPerformed(evt);
            }
        });

        botaoRemover.setText("Remover");
        botaoRemover.setEnabled(false);
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });
        botaoRemover.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                botaoRemoverPropertyChange(evt);
            }
        });

        botaoEditar.setText("Editar");
        botaoEditar.setEnabled(false);
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(botaoSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrarNovoUsuario)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarNovoUsuario)
                    .addComponent(botaoRemover)
                    .addComponent(botaoEditar)
                    .addComponent(botaoSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        BancoDeDados bancoDeDados = BancoDeDados.getInstance();
        List<Bibliotecario> listaBibliotecarios = bancoDeDados.getBibliotecario();
        
        Integer linhaSelecionada = tabelaBibliotecarios.getSelectedRow();
        Bibliotecario bibliotecario = listaBibliotecarios.get(linhaSelecionada);


        // Cria e exibe a nova tela de cadastro
        CadastroBibliotecario telaCadastroBibliotecario = new CadastroBibliotecario(
                bibliotecario.getId(),
                bibliotecario.getNome(),
                bibliotecario.getCpf(),
                bibliotecario.getGenero(),
                bibliotecario.getUsuario(),
                bibliotecario.getSenha()
        );
        
        Integer id = Integer.parseInt(tabelaBibliotecarios.getValueAt(linhaSelecionada, 0).toString());
        // Adiciona um listener para quando a tela de cadastro for fechada
        telaCadastroBibliotecario.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                // Atualiza a tabela quando a tela de cadastro for fechada
                atualizarTabela();
            }
        });

        telaCadastroBibliotecario.setVisible(true);
        telaCadastroBibliotecario.setLocationRelativeTo(null);  // Centraliza a nova tela
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void cadastrarNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarNovoUsuarioActionPerformed
        // Cria e exibe a nova tela de cadastro
        CadastroBibliotecario telaCadastroBibliotecario = new CadastroBibliotecario();

        // Adiciona um listener para quando a tela de cadastro for fechada
        telaCadastroBibliotecario.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                // Atualiza a tabela quando a tela de cadastro for fechada
                atualizarTabela();
            }
        });

        telaCadastroBibliotecario.setVisible(true);
        telaCadastroBibliotecario.setLocationRelativeTo(null);  // Centraliza a nova tela
    }//GEN-LAST:event_cadastrarNovoUsuarioActionPerformed

    private void botaoRemoverPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_botaoRemoverPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoRemoverPropertyChange

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        int resposta = JOptionPane.showConfirmDialog(
            this, 
            "Tem certeza que deseja remover este bibliotecário?", 
            "Confirmação de remoção", 
            JOptionPane.YES_NO_OPTION
        );

        if (resposta == JOptionPane.YES_OPTION) {
            BancoDeDados bancoDeDados = BancoDeDados.getInstance();
            List<Bibliotecario> listaBibliotecarios = bancoDeDados.getBibliotecario();
            Integer linhaSelecionada = tabelaBibliotecarios.getSelectedRow();

            Integer id = Integer.parseInt(tabelaBibliotecarios.getValueAt(linhaSelecionada, 0).toString());
            Boolean sucesso = bancoDeDados.removeBibliotecarioPorId(id);
            if (sucesso) {
                JOptionPane.showMessageDialog(null, "Bibliotecário removido com sucesso!", "Sucesso", JOptionPane.PLAIN_MESSAGE);

                // Atualiza a tabela após a remoção
                atualizarTabela();
            } else {
                JOptionPane.showMessageDialog(null, "ERRO AO REMOVER USUÁRIO", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_botaoRemoverActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        dispose();
    }//GEN-LAST:event_botaoSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaBibliotecarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaBibliotecarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaBibliotecarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaBibliotecarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListaBibliotecarios telaListarBibliotecarios = new ListaBibliotecarios();
                telaListarBibliotecarios.setVisible(true);
                telaListarBibliotecarios.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton cadastrarNovoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaBibliotecarios;
    // End of variables declaration//GEN-END:variables
}
