/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bceplus;

/**
 *
 * @author pedro
 */
public class ListaUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ListaUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ladoEsquerdo = new javax.swing.JPanel();
        areaTitulo = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();
        areaBtnAdmin1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        areaBtnAdmin = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        areaBtnBibliotecario = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        areaBtnUsuario = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ladoDireito = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
<<<<<<< HEAD
=======
        setPreferredSize(new java.awt.Dimension(822, 600));
>>>>>>> origin/pedro
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        ladoEsquerdo.setBackground(new java.awt.Color(255, 255, 255));
        ladoEsquerdo.setMaximumSize(new java.awt.Dimension(2000, 32767));
        ladoEsquerdo.setPreferredSize(new java.awt.Dimension(176, 524));
        ladoEsquerdo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        areaTitulo.setBackground(new java.awt.Color(255, 255, 255));
        areaTitulo.setPreferredSize(new java.awt.Dimension(176, 110));

        txtTitulo.setBackground(new java.awt.Color(204, 204, 204));
        txtTitulo.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(51, 51, 51));
        txtTitulo.setText("Administrador");

        javax.swing.GroupLayout areaTituloLayout = new javax.swing.GroupLayout(areaTitulo);
        areaTitulo.setLayout(areaTituloLayout);
        areaTituloLayout.setHorizontalGroup(
            areaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
            .addGroup(areaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(areaTituloLayout.createSequentialGroup()
                    .addGap(0, 18, Short.MAX_VALUE)
                    .addComponent(txtTitulo)
                    .addGap(0, 19, Short.MAX_VALUE)))
        );
        areaTituloLayout.setVerticalGroup(
            areaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
            .addGroup(areaTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(areaTituloLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtTitulo)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ladoEsquerdo.add(areaTitulo);

        areaBtnAdmin1.setBackground(new java.awt.Color(255, 255, 255));
        areaBtnAdmin1.setPreferredSize(new java.awt.Dimension(176, 30));

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("Roboto Condensed", 1, 13)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 51));
        jButton5.setText("Gerar Relatório");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        areaBtnAdmin1.add(jButton5);

        ladoEsquerdo.add(areaBtnAdmin1);

        areaBtnAdmin.setBackground(new java.awt.Color(255, 255, 255));
        areaBtnAdmin.setPreferredSize(new java.awt.Dimension(176, 110));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assetUsuario.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        areaBtnAdmin.add(jButton2);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adicionar Usuário");
        jLabel1.setPreferredSize(new java.awt.Dimension(176, 17));
        areaBtnAdmin.add(jLabel1);

        ladoEsquerdo.add(areaBtnAdmin);

        areaBtnBibliotecario.setBackground(new java.awt.Color(255, 255, 255));
        areaBtnBibliotecario.setPreferredSize(new java.awt.Dimension(176, 110));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assetUsuario.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        areaBtnBibliotecario.add(jButton3);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Remover Usuário");
        jLabel2.setPreferredSize(new java.awt.Dimension(176, 17));
        areaBtnBibliotecario.add(jLabel2);

        ladoEsquerdo.add(areaBtnBibliotecario);

        areaBtnUsuario.setBackground(new java.awt.Color(255, 255, 255));
        areaBtnUsuario.setPreferredSize(new java.awt.Dimension(176, 110));

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/assetUsuario.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        areaBtnUsuario.add(jButton4);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Atualizar Usuário");
        jLabel3.setPreferredSize(new java.awt.Dimension(176, 17));
        areaBtnUsuario.add(jLabel3);

        ladoEsquerdo.add(areaBtnUsuario);

        getContentPane().add(ladoEsquerdo);

        ladoDireito.setBackground(new java.awt.Color(204, 204, 204));
        ladoDireito.setPreferredSize(new java.awt.Dimension(408, 524));
        ladoDireito.setLayout(new javax.swing.BoxLayout(ladoDireito, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Lista de Usuários:");
        ladoDireito.add(jLabel4);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 500));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Pedro Eduardo Cunha Ximenes", "pecx", "Admin"},
                {"Samuel Carvalho dos Santos", "scds", "Bibliotecario"},
                {"Davy Alves de Jesus", "dadj", "Professor"},
                {"Manoel Ramos Ribeiro", "mrr", "Aluno"}
            },
            new String [] {
                "Nome da Pessoa", "Nome do Usuário", "Cargo"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.S_RESIZE_CURSOR));
        jTable1.setPreferredSize(new java.awt.Dimension(300, 400));
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);

        ladoDireito.add(jScrollPane1);

        getContentPane().add(ladoDireito);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ListaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel areaBtnAdmin;
    private javax.swing.JPanel areaBtnAdmin1;
    private javax.swing.JPanel areaBtnBibliotecario;
    private javax.swing.JPanel areaBtnUsuario;
    private javax.swing.JPanel areaTitulo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel ladoDireito;
    private javax.swing.JPanel ladoEsquerdo;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
