package bceplus;




/*
 * ClioDeDados;
import Entidades.Empreck nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author samuelcds
 */

import Entidades.BancoDeDados;
import Entidades.Emprestimo;
import Entidades.Livro;
import Entidades.Administrador;
import Entidades.Usuario;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;


public class listaUsuarios extends javax.swing.JFrame {


    public listaUsuarios() {
        initComponents();
        
        BancoDeDados bancoDeDados = BancoDeDados.getInstance();
        
        List<Usuario> listaUsuarios = bancoDeDados.getUsuario();
        tabelaUsuarios.getColumnModel().getColumn(0).setPreferredWidth(10);
        tabelaUsuarios.getColumnModel().getColumn(5).setPreferredWidth(40);
        

        DefaultTableModel modelo = (DefaultTableModel) tabelaUsuarios.getModel();
        for (Usuario usuario : listaUsuarios) {
//            List<String> titulos = emprestimo.getLivro().stream()
//                                          .map(Livro::getTitulo)
//                                          .collect(Collectors.toList());
//            System.out.println(titulos);
            modelo.addRow(new Object[]{
                usuario.getId(),
                usuario.getNome(),
                usuario.getGenero(),
                usuario.getCpf(),
                usuario.getCurso(),
                usuario.isProfessor() ? "Professor" : "Aluno",
                usuario.getUsuario(),
                usuario.getSenha()
            });
        }
        
        tabelaUsuarios.getSelectionModel().addListSelectionListener(e -> {
            // Verifica se a seleção está em curso e se há uma linha selecionada
            if (!e.getValueIsAdjusting()) {
                boolean linhaSelecionada = tabelaUsuarios.getSelectedRow() != -1;

                // Ativa os botões somente se uma linha estiver selecionada
                botaoEditar.setEnabled(linhaSelecionada);
                botaoRemover.setEnabled(linhaSelecionada);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();
        cadastrarNovoUsuario = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Annapurna SIL", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Usuários");

        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Gênero", "CPF", "Curso", "Cargo", "Usuário", "Senha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaUsuarios);

        cadastrarNovoUsuario.setText("Cadastrar Novo Usuário");
        cadastrarNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarNovoUsuarioActionPerformed(evt);
            }
        });

        botaoRemover.setText("Remover");
        botaoRemover.setEnabled(false);
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });
        botaoRemover.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                botaoRemoverPropertyChange(evt);
            }
        });

        botaoEditar.setText("Editar");
        botaoEditar.setEnabled(false);
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrarNovoUsuario)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarNovoUsuario)
                    .addComponent(botaoRemover)
                    .addComponent(botaoEditar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void cadastrarNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarNovoUsuarioActionPerformed
        // Cria e exibe a nova tela
        CadastroUsuario telaCadastroUsuario = new CadastroUsuario();
        telaCadastroUsuario.setVisible(true);
        telaCadastroUsuario.setLocationRelativeTo(null); // Centraliza a nova tela
    }//GEN-LAST:event_cadastrarNovoUsuarioActionPerformed

    private void botaoRemoverPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_botaoRemoverPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoRemoverPropertyChange

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        int resposta = JOptionPane.showConfirmDialog(
            this, 
            "Tem certeza que deseja remover este usuário?", 
            "Confirmação de remoção", 
            JOptionPane.YES_NO_OPTION
        );

        if (resposta == JOptionPane.YES_OPTION) {
            BancoDeDados bancoDeDados = BancoDeDados.getInstance();
            List<Usuario> listaUsuarios = bancoDeDados.getUsuario();
            Integer linhaSelecionada = tabelaUsuarios.getSelectedRow();
            
            
            System.out.println(linhaSelecionada);
            System.out.println(listaUsuarios.size());
            
            Integer id = Integer.parseInt(tabelaUsuarios.getValueAt(linhaSelecionada, 0).toString());
            Boolean sucesso = bancoDeDados.removeUsuarioPorId(id);
            if (sucesso) {
                JOptionPane.showMessageDialog(null, "Usuário Removido com Sucesso!", "Sucesso", JOptionPane.PLAIN_MESSAGE);
                DefaultTableModel modelo = (DefaultTableModel) tabelaUsuarios.getModel();
                modelo.setRowCount(0);  // Limpa todas as linhas da tabela

                // Recarrega a tabela com os dados atualizados
                for (Usuario usuario : listaUsuarios) {
                    String senhaOcultada;
                    senhaOcultada = "*".repeat(usuario.getSenha().length());
                    modelo.addRow(new Object[]{
                        usuario.getId(),
                        usuario.getNome(),
                        usuario.getGenero(),
                        usuario.getCpf(),
                        usuario.getCurso(),
                        usuario.isProfessor() ? "Professor" : "Aluno",
                        usuario.getUsuario(),
                        senhaOcultada
                    });
                }

            } else {
                JOptionPane.showMessageDialog(null, "ERRO AO REMOVER USUÁRIO", "Erro", JOptionPane.ERROR_MESSAGE);

            }
            
            System.out.println(linhaSelecionada);
            System.out.println(listaUsuarios.size());
        }
    }//GEN-LAST:event_botaoRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                listaUsuarios telaListarUsuarios = new listaUsuarios();
                telaListarUsuarios.setVisible(true);
                telaListarUsuarios.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton cadastrarNovoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaUsuarios;
    // End of variables declaration//GEN-END:variables
}
