/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import Entidades.BancoDeDados;
import java.util.List;
import Entidades.CSV;
import Entidades.Usuario;
import javax.swing.*;
import Entidades.Administrador; // Importação da classe Administrador
import Entidades.Bibliotecario; // Importação da classe Bibliotecario

/**
 *
 * @author pedro
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        BancoDeDados bancoDeDados = BancoDeDados.getInstance();
        
        List<Administrador> listaAdmin = bancoDeDados.getAdmin();
        
        System.out.println(listaAdmin.get(listaAdmin.size() - 1).getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RightComponent = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LeftComponent = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        User = new javax.swing.JPanel();
        usernameInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Password = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        passwordInput = new javax.swing.JPasswordField();
        jPanel6 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RightComponent.setBackground(new java.awt.Color(255, 255, 255));
        RightComponent.setMaximumSize(new java.awt.Dimension(1920, 1080));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 150);
        flowLayout1.setAlignOnBaseline(true);
        RightComponent.setLayout(flowLayout1);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bceLogo.png"))); // NOI18N
        RightComponent.add(jLabel5);

        getContentPane().add(RightComponent, java.awt.BorderLayout.CENTER);

        LeftComponent.setPreferredSize(new java.awt.Dimension(400, 0));

        jPanel4.setPreferredSize(new java.awt.Dimension(400, 100));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel1.setText("Bem Vindo!");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(35, 35, 35))
        );

        LeftComponent.add(jPanel4);

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 100));

        jButton1.setText("Login com Google");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        LeftComponent.add(jPanel3);

        jPanel5.setPreferredSize(new java.awt.Dimension(400, 150));

        User.setPreferredSize(new java.awt.Dimension(300, 40));
        User.setLayout(new java.awt.BorderLayout());

        usernameInput.setName(""); // NOI18N
        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });
        User.add(usernameInput, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Usuário:");
        User.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel5.add(User);

        Password.setPreferredSize(new java.awt.Dimension(300, 40));
        Password.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Senha:");
        Password.add(jLabel3, java.awt.BorderLayout.PAGE_START);
        Password.add(passwordInput, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(Password);

        jPanel6.setPreferredSize(new java.awt.Dimension(300, 30));

        jCheckBox1.setText("Manter Conectado");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Esqueci minha senha");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel4))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6);

        LeftComponent.add(jPanel5);

        jPanel7.setPreferredSize(new java.awt.Dimension(400, 100));

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        LeftComponent.add(jPanel7);

        getContentPane().add(LeftComponent, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String username = usernameInput.getText();
        String password = passwordInput.getText();

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo de usuário e senha!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            String caminhoUsuario = "src/data/DadosUsuario.csv";
            String caminhoAdmin = "src/data/DadosAdmin.csv";
            String caminhoBibliotecario = "src/data/DadosBibliotecario.csv";
            CSV csv = new CSV();

            List<Usuario> listaUsuarios = csv.CSVToListaUsuario(caminhoUsuario);
            List<Administrador> listaAdmins = csv.CSVToListaAdministrador(caminhoAdmin);
            List<Bibliotecario> listaBibliotecarios = csv.CSVToListaBibliotecario(caminhoBibliotecario);

            boolean loginSucesso = false;
            String tipoUsuario = "";

            // Verifica se é um administrador
            for (Administrador admin : listaAdmins) {
                if (username.equals(admin.getUsuario()) && password.equals(admin.getSenha())) {
                    loginSucesso = true;
                    tipoUsuario = "admin";
                    break;
                }
            }

            // Verifica se é um bibliotecário
            if (!loginSucesso) {
                for (Bibliotecario bibliotecario : listaBibliotecarios) {
                    if (username.equals(bibliotecario.getUsuario()) && password.equals(bibliotecario.getSenha())) {
                        loginSucesso = true;
                        tipoUsuario = "bibliotecario";
                        break;
                    }
                }
            }

            // Verifica se é um usuário comum (aluno/professor)
            if (!loginSucesso) {
                for (Usuario usuario : listaUsuarios) {
                    if (username.equals(usuario.getUsuario()) && password.equals(usuario.getSenha())) {
                        loginSucesso = true;
                        tipoUsuario = usuario.isCadastrado() ? "professor" : "comum";
                        break;
                    }
                }
            }

            if (loginSucesso) {
                JOptionPane.showMessageDialog(null, "Acesso liberado!", "Sucesso", JOptionPane.PLAIN_MESSAGE);

                // Abre a tela de menu com o tipo de usuário
                final String tipoUsuarioFinal = tipoUsuario;

                // Abre a tela de menu com o tipo de usuário
                
               TelaMenu telaMenu = new TelaMenu(tipoUsuarioFinal);
               telaMenu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               telaMenu.setVisible(true);

                // Fecha a tela de login
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LeftComponent;
    private javax.swing.JPanel Password;
    private javax.swing.JPanel RightComponent;
    private javax.swing.JPanel User;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
