package bceplus;

import Entidades.BancoDeDados;
import java.util.List;
import Entidades.Usuario;
import javax.swing.*;
import Entidades.Administrador; // Importação da classe Administrador
import Entidades.Bibliotecario; // Importação da classe Bibliotecario

/**
 *
 * @author pedro
 */
public class Login extends javax.swing.JFrame {
    Administrador admin;
    Usuario usuario;
    Bibliotecario bibliotecario;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        newPassword.setVisible(false);
        BotaoCadastro.setVisible(false);
        BancoDeDados bancoDeDados = BancoDeDados.getInstance();
        
        List<Administrador> listaAdmin = bancoDeDados.getAdmin();
        
        System.out.println(listaAdmin.get(listaAdmin.size() - 1).getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RightComponent = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LeftComponent = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        User = new javax.swing.JPanel();
        usernameInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Password = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        passwordInputt = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        newPassword = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        newpasswordInput = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        BotaoCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RightComponent.setBackground(new java.awt.Color(255, 255, 255));
        RightComponent.setMaximumSize(new java.awt.Dimension(1920, 1080));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 150);
        flowLayout1.setAlignOnBaseline(true);
        RightComponent.setLayout(flowLayout1);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bceLogo.png"))); // NOI18N
        RightComponent.add(jLabel5);

        getContentPane().add(RightComponent, java.awt.BorderLayout.CENTER);

        LeftComponent.setPreferredSize(new java.awt.Dimension(400, 0));

        jPanel4.setPreferredSize(new java.awt.Dimension(400, 100));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        jLabel1.setText("Bem Vindo!");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(35, 35, 35))
        );

        LeftComponent.add(jPanel4);

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 100));

        jButton1.setText("Login com Google");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        LeftComponent.add(jPanel3);

        jPanel5.setPreferredSize(new java.awt.Dimension(400, 150));

        User.setPreferredSize(new java.awt.Dimension(300, 40));
        User.setLayout(new java.awt.BorderLayout());

        usernameInput.setName(""); // NOI18N
        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });
        User.add(usernameInput, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Usuário:");
        User.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel5.add(User);

        Password.setPreferredSize(new java.awt.Dimension(300, 40));
        Password.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Senha:");
        Password.add(jLabel3, java.awt.BorderLayout.PAGE_START);
        Password.add(passwordInputt, java.awt.BorderLayout.PAGE_END);

        jLabel6.setText("Senha:");
        Password.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jPanel5.add(Password);

        newPassword.setPreferredSize(new java.awt.Dimension(300, 40));
        newPassword.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("Senha:");
        newPassword.add(jLabel7, java.awt.BorderLayout.PAGE_START);
        newPassword.add(newpasswordInput, java.awt.BorderLayout.PAGE_END);

        jLabel8.setText("Nova Senha:");
        newPassword.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        jPanel5.add(newPassword);

        LeftComponent.add(jPanel5);

        jPanel7.setPreferredSize(new java.awt.Dimension(400, 100));

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        BotaoCadastro.setText("Cadastro");
        BotaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(BotaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LeftComponent.add(jPanel7);

        getContentPane().add(LeftComponent, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String username = usernameInput.getText();
        String password = passwordInputt.getText();
        System.out.println(password);

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo de usuário e senha!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            String caminhoUsuario = "src/data/DadosUsuario.csv";
            String caminhoAdmin = "src/data/DadosAdmin.csv";
            String caminhoBibliotecario = "src/data/DadosBibliotecario.csv";

            List<Usuario> listaUsuarios = BancoDeDados.getInstance().getUsuario();
            List<Administrador> listaAdmins = BancoDeDados.getInstance().getAdmin();
            List<Bibliotecario> listaBibliotecarios = BancoDeDados.getInstance().getBibliotecario();

            boolean loginSucesso = false;
            String tipoUsuario = "";

            // Verifica se é um administrador
            for (Administrador admin : listaAdmins) {
                if (username.equals(admin.getUsuario()) && password.equals(admin.getSenha())) {
                    loginSucesso = true;
                    this.admin = admin;
                    tipoUsuario = "admin";
                    break;
                }
            }

            // Verifica se é um bibliotecário
            if (!loginSucesso) {
                for (Bibliotecario bibliotecario : listaBibliotecarios) {
                    if (username.equals(bibliotecario.getUsuario()) && password.equals(bibliotecario.getSenha())) {
                        if (bibliotecario.getPrimeiroLogin() == true) {
                            newPassword.setVisible(true);
                            BotaoCadastro.setVisible(true);
                        } else {
                            loginSucesso = true;
                            this.bibliotecario = bibliotecario;
                            tipoUsuario = "bibliotecario";
                            break;
                        }
                    }
                }
            }

            // Verifica se é um usuário comum (aluno/professor)
            if (!loginSucesso) {
                for (Usuario usuario : listaUsuarios) {
                    if (username.equals(usuario.getUsuario()) && password.equals(usuario.getSenha())) {
                        loginSucesso = true;
                        this.usuario = usuario;
                        tipoUsuario = usuario.isCadastrado() ? "professor" : "comum";
                        break;
                    }
                }
            }

            if (loginSucesso) {
                JOptionPane.showMessageDialog(null, "Acesso liberado!", "Sucesso", JOptionPane.PLAIN_MESSAGE);

                // Abre a tela de menu com o tipo de usuário
                final String tipoUsuarioFinal = tipoUsuario;

                // Abre a tela de menu com o tipo de usuário
                if (tipoUsuarioFinal == "admin") {
                    TelaMenu telaMenu = new TelaMenu(admin);
                    telaMenu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    telaMenu.setVisible(true);
                    telaMenu.setLocationRelativeTo(null);
                    System.out.println("Entrando como admin!");
                }
                
                if (tipoUsuarioFinal == "bibliotecario") {
                    TelaMenu telaMenu = new TelaMenu(bibliotecario);
                    telaMenu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    telaMenu.setVisible(true);
                    telaMenu.setLocationRelativeTo(null);
                    System.out.println("Entrando como Bibliotecario!");
                }
                
                if ((tipoUsuarioFinal == "comum") || (tipoUsuarioFinal == "professor")) {
                    TelaMenu telaMenu = new TelaMenu(usuario);
                    telaMenu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    telaMenu.setVisible(true);
                    telaMenu.setLocationRelativeTo(null);
                    System.out.println("Entrando como Usuario!");
                }
                

                // Fecha a tela de login
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BotaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroActionPerformed
        String username = usernameInput.getText();
        String password = passwordInputt.getText();
        String newPassword = newpasswordInput.getText();
         if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo de usuário e senha!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            List<Bibliotecario> listaBibliotecarios = BancoDeDados.getInstance().getBibliotecario();
            for (Bibliotecario bibliotecario : listaBibliotecarios) {
                if (username.equals(bibliotecario.getUsuario()) && password.equals(bibliotecario.getSenha())) {
                    if (!newPassword.isEmpty()) {
                        bibliotecario.setSenha(newPassword);
                        bibliotecario.setPrimeiroLogin(false);
                        TelaMenu telaMenu = new TelaMenu(bibliotecario);
                        telaMenu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                        telaMenu.setVisible(true);
                        telaMenu.setLocationRelativeTo(null);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Crie uma nova senha", "Erro", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
        
    }//GEN-LAST:event_BotaoCadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastro;
    private javax.swing.JPanel LeftComponent;
    private javax.swing.JPanel Password;
    private javax.swing.JPanel RightComponent;
    private javax.swing.JPanel User;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel newPassword;
    private javax.swing.JPasswordField newpasswordInput;
    private javax.swing.JPasswordField passwordInputt;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
